/* Offline journal editor and list; all user text is rendered as text or input values. */
(function(root){
'use strict';
root.JournalNotebook={create({data,groups,select,download,onChange}){
 const N=JournalNotes,M=JournalModel,$=id=>document.getElementById(id),statuses={todo:'ยังไม่รีวิว',reviewing:'กำลังรีวิว',reviewed:'รีวิวแล้ว'};
 const ids=groups.map(g=>N.identity(g.trades[0].account_login,g.trades[0].account_server,g.id,!!data.demo));
 const idFor=g=>ids[groups.indexOf(g)];let storage=null,selected=null,pending=[];try{storage=window.localStorage;}catch(e){}
 const store=N.create(storage,data.notes?N.parseBundle(data.notes):[]);
 const form=$('noteForm');
 function note(g){return store.get(idFor(g));}
 function label(g){return statuses[note(g).fields.status];}
 function matching(g,q){const r=note(g);return [g.symbol,g.id,r.fields.setup,r.fields.tags,r.fields.before,r.fields.after].join(' ').toLowerCase().includes(q);}
 function cell(tr,value){const td=document.createElement('td');td.textContent=value;tr.appendChild(td);return td;}
 function list(){const q=$('listSearch').value.toLowerCase(),filter=$('reviewFilter').value;$('journalRows').replaceChildren();const filtered=groups.filter(g=>matching(g,q)&&(!filter||note(g).fields.status===filter));for(const g of filtered){const r=note(g),tr=document.createElement('tr');cell(tr,M.stamp(g.first));cell(tr,g.symbol+' · #'+g.id);const net=cell(tr,g.net.toFixed(2)+' '+g.currency);net.className=g.net>=0?'positive':'negative';cell(tr,r.fields.setup||'—');cell(tr,r.fields.tags||'—');cell(tr,label(g));cell(tr,r.updatedAt?new Date(r.updatedAt).toLocaleString('th-TH'):'—');const button=document.createElement('button');button.className='action';button.textContent='เปิด / แก้บันทึก';button.setAttribute('aria-label','เปิดบันทึก position '+g.id);button.onclick=()=>select(g);const td=document.createElement('td');td.appendChild(button);tr.appendChild(td);$('journalRows').appendChild(tr);}if(!filtered.length){const tr=document.createElement('tr'),td=cell(tr,'ไม่พบรายการที่ตรงกับตัวกรอง');td.colSpan=8;$('journalRows').appendChild(tr);}const reviewed=groups.filter(g=>note(g).fields.status==='reviewed').length;$('reviewCount').textContent=groups.length+' รายการ · รีวิวแล้ว '+reviewed+' · แสดง '+filtered.length;}
 function showList(){selected=null;$('overview').hidden=false;$('detail').hidden=true;location.hash='list';list();}
 function status(){if(!selected)return;const s=store.state(idFor(selected));$('noteSaveState').className=s.dirty||s.blocked?'notice':'fine';$('noteSaveState').textContent=s.dirty?'ยังไม่เซฟลง browser: '+s.error+' — ข้อความยังอยู่ในหน้านี้ ให้ดาวน์โหลด HTML หรือสำรอง JSON ก่อนปิด':s.blocked?'อ่าน storage ไม่สำเร็จ: '+s.error+' — ใช้ดาวน์โหลด HTML / สำรอง JSON เพื่อเก็บบันทึก':s.record?'บันทึกส่วนตัว · '+new Date(s.record.updatedAt).toLocaleString('th-TH')+' · เซฟเมื่อแก้ไขใน browser นี้ (ไฟล์ HTML ต้นฉบับยังไม่ถูกเขียนทับ)':'เริ่มเขียนได้เลย • จะเซฟอัตโนมัติใน browser นี้เมื่อแก้ไข';$('draftWarning').hidden=!store.dirty();}
 function persist(){if(!selected)return;const values=Object.fromEntries(N.fields.map(f=>[f,form.elements.namedItem(f).value]));const checklist=[...$('checklist').children].map(row=>({label:row.querySelector('input[type=text]').value,checked:row.querySelector('input[type=checkbox]').checked}));try{store.save(idFor(selected),values,checklist);status();list();onChange?.();}catch(e){$('noteSaveState').textContent='ยังไม่เซฟ: '+e.message;}}
 function checkRow(item){const row=document.createElement('div');row.className='check-row';const box=document.createElement('input');box.type='checkbox';box.checked=item.checked;box.setAttribute('aria-label','ผ่านเงื่อนไข '+item.label);const input=document.createElement('input');input.type='text';input.maxLength=500;input.value=item.label;input.placeholder='เขียนเงื่อนไขของคุณ';input.setAttribute('aria-label','ข้อความเช็กลิสต์');input.oninput=()=>box.setAttribute('aria-label','ผ่านเงื่อนไข '+input.value);const remove=document.createElement('button');remove.type='button';remove.className='action';remove.textContent='ลบ';remove.setAttribute('aria-label','ลบข้อเช็กลิสต์');remove.onclick=()=>{row.remove();persist();};row.append(box,input,remove);$('checklist').appendChild(row);}
 function open(g){selected=g;$('overview').hidden=true;$('detail').hidden=false;const r=note(g);for(const f of N.fields)form.elements.namedItem(f).value=r.fields[f];$('checklist').replaceChildren();r.checklist.forEach(checkRow);status();}
 form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',persist);form.addEventListener('change',persist);
 $('addCheck').onclick=()=>{if($('checklist').children.length>=100)return;checkRow({label:'',checked:false});$('checklist').lastChild.querySelector('input[type=text]').focus();persist();};
 $('showList').onclick=showList;$('backList').onclick=showList;$('listSearch').oninput=list;$('reviewFilter').onchange=list;
 $('backupNotes').onclick=()=>{download(JSON.stringify(N.bundle(store.records(ids)),null,2),'journal-notes-'+(data.demo?'DEMO-':'')+new Date().toISOString().slice(0,10)+'.json','application/json');$('transferStatus').textContent='ส่งไฟล์ให้ browser ดาวน์โหลดแล้ว ตรวจโฟลเดอร์ Downloads และเก็บ JSON ไว้สำหรับนำเข้าในรายงานใหม่';};
 $('chooseNotes').onclick=()=>$('importNotes').click();
 $('importNotes').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10000000)throw Error('ไฟล์ใหญ่เกิน 10 MB');const all=N.parseBundle(await file.text()),allowed=new Set(ids.map(N.key));pending=all.filter(r=>allowed.has(N.key(r.identity)));const conflicts=pending.filter(r=>store.state(r.identity).record).length;$('importSummary').textContent='พบ '+pending.length+' บันทึกที่ตรงกับบัญชีและ positions ในรายงานนี้ · มีบันทึกอยู่แล้ว '+conflicts+' · ไม่ตรงรายงาน '+(all.length-pending.length)+' (ข้าม)';$('replaceNotes').checked=false;$('importPreview').hidden=false;$('applyImport').disabled=!pending.length;}catch(error){pending=[];$('importPreview').hidden=true;$('transferStatus').textContent='นำเข้าไม่ได้: '+error.message;}};
 $('cancelImport').onclick=()=>{pending=[];$('importPreview').hidden=true;};
 $('applyImport').onclick=()=>{try{const result=store.importRecords(pending,$('replaceNotes').checked);$('transferStatus').textContent='นำเข้า '+result.added+' · เก็บบันทึกเดิม '+result.skipped+(result.failed?' · '+result.failed+' บันทึกยังเซฟลง browser ไม่สำเร็จ ให้สำรองก่อนปิด':'');pending=[];$('importPreview').hidden=true;list();if(selected)open(selected);$('draftWarning').hidden=!store.dirty();onChange?.();}catch(e){$('transferStatus').textContent='นำเข้าไม่ได้: '+e.message;}};
 window.addEventListener('beforeunload',e=>{if(store.dirty()){e.preventDefault();e.returnValue='';}});
 window.addEventListener('storage',e=>{if(e.key?.startsWith(N.prefix)){$('transferStatus').textContent='มีบันทึกเปลี่ยนจากหน้าต่างอื่น ถ้าหน้านี้มีข้อความที่ต้องการเก็บ ให้สำรอง JSON ก่อนเปิดรายงานใหม่';}});
 list();return {open,showList,list,label,matching,notes:g=>N.bundle(store.records(g?[idFor(g)]:ids))};
}};
})(globalThis);
