#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <vector>
constexpr double EMPTY_VALUE=std::numeric_limits<double>::max();
#define MathIsValidNumber std::isfinite
template<typename A,typename B> double MathMax(A a,B b) { return std::max(double(a),double(b)); }
#include "../../MQL5/Indicators/TVStyleMACD/MACDCore.mqh"
int InpFastLength=12,InpSlowLength=26,InpSignalLength=9;
ENUM_TV_MA InpOscillatorMA=TV_EMA,InpSignalMA=TV_EMA;
bool InpFourColorHistogram=true;
std::vector<double> Src,Fast,Slow,MACD,Signal,Histogram,Palette,FastSum,SlowSum,SignalSum;
// Generated by the runner from the production mq5: not a copied algorithm.
#include "macd_bar_under_test.hpp"
int checks=0;
void check(bool good,const char* reason) {
    ++checks; if(!good) { std::cerr<<"FAIL: "<<reason<<'\n'; std::exit(1); }
}
bool near(double a,double b) {
    if(a==EMPTY_VALUE || b==EMPTY_VALUE) return a==b;
    return std::abs(a-b)<1e-9;
}
void resize(int n) {
    Src.resize(n); Fast.resize(n); Slow.resize(n); MACD.resize(n); Signal.resize(n);
    Histogram.resize(n); Palette.resize(n); FastSum.resize(n); SlowSum.resize(n); SignalSum.resize(n);
}
// Independent finite-window SMA / explicit geometric-weight EMA oracle.
double reference(const std::vector<double>& src,int last,int length,ENUM_TV_MA mode) {
    int first=0;
    while(first<=last && src[first]==EMPTY_VALUE) ++first;
    if(first>last) return EMPTY_VALUE;
    int count=last-first+1;
    if(mode==TV_SMA) {
        if(count<length) return EMPTY_VALUE;
        long double sum=0;
        for(int j=last-length+1;j<=last;++j) sum+=src[j];
        return double(sum/length);
    }
    long double alpha=2.L/(length+1.L),beta=1.L-alpha;
    long double value=src[first]*std::pow(beta,last-first);
    for(int j=first+1;j<=last;++j) value+=alpha*src[j]*std::pow(beta,last-j);
    return double(value);
}
void verify(const std::vector<double>& prices) {
    int n=int(prices.size()); resize(n);
    std::vector<double> ref_macd(n,EMPTY_VALUE);
    for(int i=0;i<n;++i) {
        CalculateBar(i,prices[i]);
        double fast=reference(prices,i,InpFastLength,InpOscillatorMA);
        double slow=reference(prices,i,InpSlowLength,InpOscillatorMA);
        check(near(Fast[i],fast),"fast MA equals independent oracle");
        check(near(Slow[i],slow),"slow MA equals independent oracle");
        if(fast!=EMPTY_VALUE && slow!=EMPTY_VALUE) ref_macd[i]=fast-slow;
        check(near(MACD[i],ref_macd[i]),"MACD equals fast minus slow");
        double signal=reference(ref_macd,i,InpSignalLength,InpSignalMA);
        check(near(Signal[i],signal),"Signal equals independent MA of MACD");
        check(near(Histogram[i],signal==EMPTY_VALUE ? EMPTY_VALUE : ref_macd[i]-signal),"histogram equals MACD minus Signal");
    }
    auto before=Histogram;
    for(int k=0;k<50;++k) CalculateBar(n-1,prices[n-1]);
    check(near(Histogram.back(),before.back()),"same tick repeatedly recalculated without recursive drift");
    CalculateBar(n-1,prices[n-1]+3.25);
    CalculateBar(n-1,prices[n-1]);
    check(near(Histogram.back(),before.back()),"intrabar change and reversal restore original value");
    if(n>1) check(near(Histogram[n-2],before[n-2]),"tick never changes previous closed bar");
}
int main() {
    check(TVPrice(TV_CLOSE,10,14,8,12)==12,"close source");
    check(TVPrice(TV_OPEN,10,14,8,12)==10,"open source");
    check(TVPrice(TV_HIGH,10,14,8,12)==14,"high source");
    check(TVPrice(TV_LOW,10,14,8,12)==8,"low source");
    check(TVPrice(TV_HL2,10,14,8,12)==11,"hl2 source");
    check(near(TVPrice(TV_HLC3,10,14,8,12),34./3),"hlc3 source");
    check(TVPrice(TV_OHLC4,10,14,8,12)==11,"ohlc4 differs from MT5 weighted close");
    check(TVPrice(TV_HLCC4,10,14,8,12)==11.5,"hlcc4 source");
    check(TVHistogramColor(2,1,true)==0,"above zero rising");
    check(TVHistogramColor(1,2,true)==1,"above zero falling");
    check(TVHistogramColor(-1,-2,true)==2,"below zero rising");
    check(TVHistogramColor(-2,-1,true)==3,"below zero falling");
    check(TVHistogramColor(1,1,true)==1,"positive plateau");
    check(TVHistogramColor(-1,-1,true)==3,"negative plateau");
    check(TVHistogramColor(0,EMPTY_VALUE,true)==1,"first zero uses non-rising branch");
    check(TVHistogramColor(1,2,false)==0,"two-color positive");
    check(TVHistogramColor(-1,-2,false)==3,"two-color negative");
    check(TVHistogramCross(-1,1)==1,"positive histogram crossing");
    check(TVHistogramCross(1,-1)==-1,"negative histogram crossing");
    check(TVHistogramCross(0,-1)==-1,"zero to negative");
    check(TVHistogramCross(-1,0)==0,"ending exactly at zero is not a crossing");
    check(TVHistogramCross(EMPTY_VALUE,1)==0,"no alert at warmup");
    check(TVMappedIndex(4,5,false,false,false)==4,"historical MTF never uses developing final value");
    check(TVMappedIndex(4,5,true,false,false)==5,"live MTF permits developing source if enabled");
    check(TVMappedIndex(4,5,true,true,false)==-1,"wait-close omits unconfirmed chart slots");
    check(TVMappedIndex(5,6,false,true,true)==5,"wait-close plots at confirmation slot");
    check(TVMappedIndex(-1,-1,false,false,false)==-1,"no source history returns empty");
    double sum=0;
    check(TVMovingAverage(TV_EMA,0,1,1,EMPTY_VALUE,0,0,sum)==EMPTY_VALUE,"invalid period");
    check(TVMovingAverage(TV_EMA,3,1,NAN,EMPTY_VALUE,0,0,sum)==EMPTY_VALUE,"invalid source");
    std::vector<double> fixture;
    for(int i=0;i<512;++i) fixture.push_back(100+10*std::sin(i*.13)+i*.01);
    int lengths[][3]={{12,26,9},{1,1,1},{2,5,3},{26,12,9},{3,7,1},{600,700,30}};
    for(int osc=0;osc<2;++osc) for(int sig=0;sig<2;++sig) {
        InpOscillatorMA=ENUM_TV_MA(osc); InpSignalMA=ENUM_TV_MA(sig);
        for(auto& lengths_set:lengths) {
            InpFastLength=lengths_set[0]; InpSlowLength=lengths_set[1]; InpSignalLength=lengths_set[2];
            verify(fixture);
            verify(std::vector<double>(50,3650));
        }
    }
    InpOscillatorMA=TV_EMA; InpSignalMA=TV_EMA;
    InpFastLength=12; InpSlowLength=26; InpSignalLength=9;
    resize(100); for(int i=0;i<100;++i) CalculateBar(i,fixture[i]);
    resize(512); for(int i=99;i<512;++i) CalculateBar(i,fixture[i]);
    auto appended=Histogram;
    verify(fixture);
    for(int i=0;i<512;++i) check(near(appended[i],Histogram[i]),"incremental new bars equal a fresh full calculation");
    std::cout<<"PASS: "<<checks<<" MACD checks, production core + CalculateBar, independent MA oracle\n";
}
