#!/usr/bin/env python3
"""Embed the offline report sources for MQL; no third-party assets."""
from pathlib import Path
import json
import sys
root=Path(__file__).resolve().parents[1]
folder=root/'MQL5/Scripts/TradeJournal'
html=(folder/'Report.html').read_text().replace('__JOURNAL_MODEL__',(folder/'ReportModel.js').read_text()).replace('__JOURNAL_NOTES__',(folder/'NotesModel.js').read_text()).replace('__JOURNAL_NOTEBOOK__',(folder/'ReportNotebook.js').read_text()).replace('__JOURNAL_UI__',(folder/'ReportUI.js').read_text())
assert html.count('__JOURNAL_DATA__')==1
encoded='// Generated by scripts/build-journal-template.py; edit Report.html / ReportModel.js / NotesModel.js / ReportNotebook.js / ReportUI.js.\nconst string JR_TEMPLATE=\n'
encoded+='\n'.join(json.dumps(line,ensure_ascii=False) for line in html.splitlines(keepends=True))+';\n'
target=folder/'JournalReportTemplate.mqh'
if '--check' in sys.argv:
    assert target.read_text()==encoded,'Regenerate JournalReportTemplate.mqh'
else:
    target.write_text(encoded)
print('Journal HTML template verified' if '--check' in sys.argv else 'Journal HTML template generated')
